name: game_tracker
description: "Game Tracking App for Card Games"
publish_to: 'none'
version: 0.0.1+21

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  material_symbols_icons: ^4.2815.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  provider: ^6.1.5
  skeletonizer: ^2.1.0+1
  uuid: ^4.5.2
  file_picker: ^10.3.6
  json_schema: ^5.2.2
  file_saver: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.27.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/schema.json
