name: game_tracker
description: "Game Tracking App for Card Games"
publish_to: 'none'
version: 0.0.8+227

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  clock: ^1.1.2
  cupertino_icons: ^1.0.6
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  file_picker: ^10.3.6
  file_saver: ^0.3.1
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.12.0
  intl: any
  json_schema: ^5.2.2
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  skeletonizer: ^2.1.0+1
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  dart_pubspec_licenses: ^3.0.14
  drift_dev: ^2.27.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/schema.json
